import type { DashboardState, LogEvent, Opportunity, Position, ServiceHealth, UserAccount } from './types'

function note(id: string, author: string, createdAt: string, context: 'decision' | 'risk' | 'operations', text: string) {
  return { id, author, createdAt, context, text }
}

function link(
  id: string,
  title: string,
  url: string,
  uploadedBy: string,
  uploadedAt: string,
) {
  return { id, type: 'link' as const, title, url, uploadedBy, uploadedAt }
}

export const seedUsers: UserAccount[] = [
  {
    id: 'user-alex',
    name: 'Alex Chen',
    email: 'alex@polyclaw.local',
    password: 'demo1234',
    role: 'trader',
    createdAt: '2026-04-11T14:00:00.000Z',
  },
  {
    id: 'user-maya',
    name: 'Maya Patel',
    email: 'maya@polyclaw.local',
    password: 'demo1234',
    role: 'analyst',
    createdAt: '2026-04-11T14:05:00.000Z',
  },
]

export const seedOpportunities: Opportunity[] = [
  {
    id: 'opp-nba-knicks-game1',
    question: 'Will the Knicks win Game 1 vs the 76ers?',
    category: 'NBA',
    marketType: 'Series opener',
    side: 'YES',
    marketProbability: 0.48,
    modelProbability: 0.582,
    edge: 0.102,
    expectedReturn: 0.091,
    confidence: 0.917,
    liquidity: 702000,
    volume24h: 214000,
    marketDepth: 130000,
    spreadBps: 180,
    urgencyScore: 0.81,
    signalStrength: 0.88,
    discoveredAt: '2026-04-12T15:48:00.000Z',
    lastUpdatedAt: '2026-04-12T16:12:00.000Z',
    resolutionDate: '2026-04-13T23:30:00.000Z',
    timeHorizon: '2-8 hours',
    recommendedStake: 4200,
    maxStake: 7000,
    entryPriceMin: 0.47,
    entryPriceMax: 0.49,
    slippageLimitBps: 35,
    currentStage: 'new',
    statusLabel: 'Awaiting review',
    strategySummary: 'Fast-moving playoff market with improving model edge after injury and lineup updates.',
    thesis:
      'The current market is still pricing the 76ers at pre-news levels. Our model repriced bench depth and defensive matchup advantages in New York’s favor.',
    invalidation: 'Edge collapses if the price trades above 0.51 or if confirmed starting lineup swings back toward Philadelphia.',
    riskFlags: ['Injury-news sensitivity', 'Crowded market late in the day'],
    tags: ['strong-edge', 'playoff', 'positive-ev'],
    relatedExposure: 11800,
    correlationWarning: 'Already long one NBA playoff position; review correlated downside before sizing above recommendation.',
    priceHistory: [0.43, 0.44, 0.46, 0.47, 0.48],
    notes: [
      note(
        'note-opp-1',
        'Maya Patel',
        '2026-04-12T16:03:00.000Z',
        'decision',
        'Worth approving if the order can stay inside the 0.49 cap. Depth looks strong enough for a modest live fill.',
      ),
    ],
    attachments: [
      link(
        'att-opp-1',
        'Injury monitor summary',
        'https://example.com/research/knicks-injury-monitor',
        'Maya Patel',
        '2026-04-12T16:02:00.000Z',
      ),
    ],
  },
  {
    id: 'opp-soc-city-ucl',
    question: 'Will Manchester City win the Champions League quarterfinal first leg?',
    category: 'Soccer',
    marketType: 'Moneyline',
    side: 'YES',
    marketProbability: 0.64,
    modelProbability: 0.736,
    edge: 0.096,
    expectedReturn: 0.086,
    confidence: 0.922,
    liquidity: 851000,
    volume24h: 262000,
    marketDepth: 172000,
    spreadBps: 140,
    urgencyScore: 0.63,
    signalStrength: 0.84,
    discoveredAt: '2026-04-12T15:15:00.000Z',
    lastUpdatedAt: '2026-04-12T16:13:00.000Z',
    resolutionDate: '2026-04-15T20:00:00.000Z',
    timeHorizon: 'Same day',
    recommendedStake: 3800,
    maxStake: 6200,
    entryPriceMin: 0.63,
    entryPriceMax: 0.65,
    slippageLimitBps: 25,
    currentStage: 'new',
    statusLabel: 'Awaiting review',
    strategySummary: 'Stable high-confidence soccer signal with strong liquidity and tight spreads.',
    thesis:
      'Model probability sits materially above market after recent squad rotation data and home/away performance adjustments.',
    invalidation: 'Skip if liquidity thins materially or pre-match roster confirmation lowers our fair probability below 0.70.',
    riskFlags: ['Late roster volatility'],
    tags: ['soccer', 'high-liquidity', 'high-confidence'],
    relatedExposure: 0,
    priceHistory: [0.58, 0.6, 0.61, 0.63, 0.64],
    notes: [],
    attachments: [],
  },
  {
    id: 'opp-ele-pa-2028',
    question: 'Will Democrats win Pennsylvania in the 2028 presidential election?',
    category: 'Elections',
    marketType: 'State outcome',
    side: 'YES',
    marketProbability: 0.54,
    modelProbability: 0.601,
    edge: 0.061,
    expectedReturn: 0.049,
    confidence: 0.734,
    liquidity: 964000,
    volume24h: 261000,
    marketDepth: 194000,
    spreadBps: 95,
    urgencyScore: 0.34,
    signalStrength: 0.59,
    discoveredAt: '2026-04-12T13:28:00.000Z',
    lastUpdatedAt: '2026-04-12T16:11:00.000Z',
    resolutionDate: '2028-11-07T23:59:00.000Z',
    timeHorizon: 'Multi-week accumulation',
    recommendedStake: 2500,
    maxStake: 5000,
    entryPriceMin: 0.53,
    entryPriceMax: 0.55,
    slippageLimitBps: 15,
    currentStage: 'paper',
    statusLabel: 'Sent to paper',
    strategySummary: 'Lower urgency macro position being tested in paper mode before live capital is committed.',
    thesis:
      'Macro model likes current price versus longer-dated turnout and party-registration assumptions, but we want to validate thesis persistence over several refresh cycles.',
    invalidation: 'Do not promote live until the signal persists across three data refresh windows and event-specific news remains calm.',
    riskFlags: ['Long-dated event', 'Headline sensitivity'],
    tags: ['macro', 'paper-first'],
    relatedExposure: 6400,
    priceHistory: [0.52, 0.53, 0.53, 0.54, 0.54],
    notes: [
      note(
        'note-opp-2',
        'Alex Chen',
        '2026-04-12T15:11:00.000Z',
        'risk',
        'Keep this in paper for now. Long horizon plus correlated political exposure already exists live.',
      ),
    ],
    attachments: [],
  },
  {
    id: 'opp-mention-trump-speech',
    question: 'Will Trump mention tariffs at least three times in his next major speech?',
    category: 'Mentions',
    marketType: 'Speech mention count',
    side: 'YES',
    marketProbability: 0.41,
    modelProbability: 0.51,
    edge: 0.1,
    expectedReturn: 0.082,
    confidence: 0.684,
    liquidity: 286000,
    volume24h: 81000,
    marketDepth: 54000,
    spreadBps: 260,
    urgencyScore: 0.76,
    signalStrength: 0.72,
    discoveredAt: '2026-04-12T15:56:00.000Z',
    lastUpdatedAt: '2026-04-12T16:12:00.000Z',
    resolutionDate: '2026-04-13T02:00:00.000Z',
    timeHorizon: 'Intraday',
    recommendedStake: 1800,
    maxStake: 3200,
    entryPriceMin: 0.40,
    entryPriceMax: 0.42,
    slippageLimitBps: 45,
    currentStage: 'new',
    statusLabel: 'Awaiting review',
    strategySummary: 'Short-lived language model signal tied to speech topic drift and recent campaign messaging patterns.',
    thesis:
      'The mention model has picked up strong overlap between the event agenda and recent tariff messaging, while the market still prices the mention count conservatively.',
    invalidation: 'Skip if the event agenda changes or speech start time shifts materially.',
    riskFlags: ['Sparse liquidity', 'Fast-resolution event'],
    tags: ['mentions', 'headline', 'fast-market'],
    relatedExposure: 4200,
    correlationWarning: 'Mentions category is already active in live book; sizing above base recommendation may over-concentrate event risk.',
    priceHistory: [0.34, 0.36, 0.38, 0.4, 0.41],
    notes: [],
    attachments: [
      link(
        'att-opp-2',
        'Speech topic tracker',
        'https://example.com/research/tariff-topic-tracker',
        'Alex Chen',
        '2026-04-12T16:00:00.000Z',
      ),
    ],
  },
  {
    id: 'opp-cricket-mi-csk',
    question: 'Will Mumbai Indians beat CSK in tonight’s IPL fixture?',
    category: 'Cricket',
    marketType: 'Moneyline',
    side: 'YES',
    marketProbability: 0.52,
    modelProbability: 0.607,
    edge: 0.087,
    expectedReturn: 0.076,
    confidence: 0.911,
    liquidity: 690000,
    volume24h: 191000,
    marketDepth: 132000,
    spreadBps: 155,
    urgencyScore: 0.57,
    signalStrength: 0.82,
    discoveredAt: '2026-04-12T14:59:00.000Z',
    lastUpdatedAt: '2026-04-12T16:09:00.000Z',
    resolutionDate: '2026-04-12T23:00:00.000Z',
    timeHorizon: '4-6 hours',
    recommendedStake: 3300,
    maxStake: 5600,
    entryPriceMin: 0.51,
    entryPriceMax: 0.53,
    slippageLimitBps: 28,
    currentStage: 'new',
    statusLabel: 'Awaiting review',
    strategySummary: 'High-confidence sports position with strong depth and favorable recent form inputs.',
    thesis:
      'Model likes matchup and toss-adjusted projections. Market still underweights bowling strength and recent late-innings execution.',
    invalidation: 'Skip if expected starting XI changes materially or if price pushes through 0.54 before review.',
    riskFlags: ['Toss dependency'],
    tags: ['cricket', 'good-liquidity'],
    relatedExposure: 0,
    priceHistory: [0.47, 0.48, 0.49, 0.51, 0.52],
    notes: [],
    attachments: [],
  },
  {
    id: 'opp-soc-inter-under',
    question: 'Will Inter vs Milan finish under 2.5 goals?',
    category: 'Soccer',
    marketType: 'Totals',
    side: 'YES',
    marketProbability: 0.53,
    modelProbability: 0.592,
    edge: 0.062,
    expectedReturn: 0.052,
    confidence: 0.895,
    liquidity: 320000,
    volume24h: 98000,
    marketDepth: 73000,
    spreadBps: 200,
    urgencyScore: 0.51,
    signalStrength: 0.74,
    discoveredAt: '2026-04-12T13:04:00.000Z',
    lastUpdatedAt: '2026-04-12T16:08:00.000Z',
    resolutionDate: '2026-04-13T19:45:00.000Z',
    timeHorizon: 'Overnight',
    recommendedStake: 2400,
    maxStake: 4200,
    entryPriceMin: 0.52,
    entryPriceMax: 0.54,
    slippageLimitBps: 30,
    currentStage: 'approved',
    statusLabel: 'Approved for live execution',
    strategySummary: 'Already approved by research, pending execution confirmation from the desk.',
    thesis:
      'Tempo-adjusted scoring model points to lower scoring than market price implies. Cross-checks with injuries support the under.',
    invalidation: 'Cancel if lineup news increases attacking strength or if market reprices below 0.51.',
    riskFlags: ['Lineup sensitivity'],
    tags: ['approved', 'awaiting-execution'],
    relatedExposure: 6100,
    reviewer: 'Maya Patel',
    reviewedAt: '2026-04-12T15:43:00.000Z',
    priceHistory: [0.49, 0.5, 0.51, 0.52, 0.53],
    notes: [],
    attachments: [],
  },
  {
    id: 'opp-ele-wi-margin',
    question: 'Will Wisconsin be decided by less than 1.5% margin?',
    category: 'Elections',
    marketType: 'Margin band',
    side: 'YES',
    marketProbability: 0.51,
    modelProbability: 0.562,
    edge: 0.052,
    expectedReturn: 0.039,
    confidence: 0.671,
    liquidity: 320000,
    volume24h: 88000,
    marketDepth: 68000,
    spreadBps: 165,
    urgencyScore: 0.29,
    signalStrength: 0.53,
    discoveredAt: '2026-04-12T12:40:00.000Z',
    lastUpdatedAt: '2026-04-12T16:01:00.000Z',
    resolutionDate: '2028-11-07T23:59:00.000Z',
    timeHorizon: 'Portfolio hedge candidate',
    recommendedStake: 1500,
    maxStake: 3000,
    entryPriceMin: 0.50,
    entryPriceMax: 0.52,
    slippageLimitBps: 20,
    currentStage: 'rejected',
    statusLabel: 'Rejected',
    strategySummary: 'Rejected after review because the edge was too slow-moving relative to current political exposure.',
    thesis:
      'Still a decent signal, but not compelling enough given long-dated capital lockup and existing elections book.',
    invalidation: 'Re-open only if fair probability improves or hedging needs change.',
    riskFlags: ['Capital tie-up'],
    tags: ['rejected'],
    relatedExposure: 9600,
    reviewer: 'Alex Chen',
    reviewedAt: '2026-04-12T15:06:00.000Z',
    priceHistory: [0.49, 0.49, 0.5, 0.5, 0.51],
    notes: [
      note(
        'note-opp-3',
        'Alex Chen',
        '2026-04-12T15:06:00.000Z',
        'decision',
        'Passing for now. Long-dated and not enough incremental edge versus our existing election positioning.',
      ),
    ],
    attachments: [],
  },
  {
    id: 'opp-nba-lakers-spread',
    question: 'Will the Lakers cover -4.5 vs the Suns?',
    category: 'NBA',
    marketType: 'Spread',
    side: 'YES',
    marketProbability: 0.57,
    modelProbability: 0.638,
    edge: 0.068,
    expectedReturn: 0.058,
    confidence: 0.909,
    liquidity: 500000,
    volume24h: 150000,
    marketDepth: 109000,
    spreadBps: 190,
    urgencyScore: 0.58,
    signalStrength: 0.79,
    discoveredAt: '2026-04-12T14:48:00.000Z',
    lastUpdatedAt: '2026-04-12T16:10:00.000Z',
    resolutionDate: '2026-04-13T01:00:00.000Z',
    timeHorizon: 'Tonight',
    recommendedStake: 2600,
    maxStake: 4300,
    entryPriceMin: 0.56,
    entryPriceMax: 0.58,
    slippageLimitBps: 30,
    currentStage: 'new',
    statusLabel: 'Awaiting review',
    strategySummary: 'Good liquidity and strong model confidence, but current exposure needs a quick desk check.',
    thesis:
      'Spread model shows consistent edge and no major market drift against us yet.',
    invalidation: 'Pull if the line moves through 0.59 or if injury news flips pace assumptions.',
    riskFlags: ['NBA correlation'],
    tags: ['nba', 'strong-edge'],
    relatedExposure: 11800,
    correlationWarning: 'Same category exposure already sits above baseline. Either trim another NBA trade or keep size conservative.',
    priceHistory: [0.51, 0.53, 0.54, 0.56, 0.57],
    notes: [],
    attachments: [],
  },
]

export const seedLivePositions: Position[] = [
  {
    id: 'pos-live-celtics',
    opportunityId: 'seed-celtics',
    environment: 'live',
    question: 'Will the Celtics beat the Heat on April 14?',
    category: 'NBA',
    marketType: 'Moneyline',
    side: 'YES',
    shares: 4098.36,
    stake: 2500,
    entryPrice: 0.61,
    currentPrice: 0.646,
    liquidationValue: 2647.54,
    unrealizedPnl: 147.54,
    status: 'open',
    openedAt: '2026-04-11T18:12:00.000Z',
    updatedAt: '2026-04-12T16:12:00.000Z',
    modelView: 'Still favorable; edge has narrowed but remains positive.',
    thesisAtEntry: 'Early heat fatigue signals and matchup strength favored Boston.',
    exitGuidance: 'Hold unless price exceeds 0.67 before close.',
    relatedStrategy: 'sports-momentum-v2',
    notes: [
      note(
        'note-pos-1',
        'Alex Chen',
        '2026-04-12T12:22:00.000Z',
        'risk',
        'No scaling needed unless we add another NBA position tonight.',
      ),
    ],
    tags: ['nba', 'live-book'],
    priceHistory: [0.6, 0.612, 0.626, 0.638, 0.646],
  },
  {
    id: 'pos-live-arsenal',
    opportunityId: 'seed-arsenal',
    environment: 'live',
    question: 'Will Arsenal beat Tottenham in the North London derby?',
    category: 'Soccer',
    marketType: 'Moneyline',
    side: 'YES',
    shares: 3898.3,
    stake: 2300,
    entryPrice: 0.59,
    currentPrice: 0.618,
    liquidationValue: 2409.15,
    unrealizedPnl: 109.15,
    status: 'watch',
    openedAt: '2026-04-12T10:03:00.000Z',
    updatedAt: '2026-04-12T16:10:00.000Z',
    modelView: 'Thesis intact, but watch roster confirmation this afternoon.',
    thesisAtEntry: 'Home edge plus rotation data created a short-lived pricing gap.',
    exitGuidance: 'Continue holding unless lineup news moves fair value below 0.60.',
    relatedStrategy: 'soccer-core-v1',
    notes: [],
    tags: ['soccer', 'watch-list'],
    priceHistory: [0.582, 0.59, 0.602, 0.611, 0.618],
  },
  {
    id: 'pos-live-pa-2028',
    opportunityId: 'seed-pa',
    environment: 'live',
    question: 'Will Democrats win Pennsylvania in the 2028 presidential election?',
    category: 'Elections',
    marketType: 'State outcome',
    side: 'YES',
    shares: 14814.81,
    stake: 8000,
    entryPrice: 0.54,
    currentPrice: 0.561,
    liquidationValue: 8311.11,
    unrealizedPnl: 311.11,
    status: 'open',
    openedAt: '2026-04-02T14:12:00.000Z',
    updatedAt: '2026-04-12T16:09:00.000Z',
    modelView: 'Long-dated thesis unchanged; edge remains modest but positive.',
    thesisAtEntry: 'Registration and turnout models were materially above market.',
    exitGuidance: 'Treat as portfolio ballast unless a faster election signal replaces it.',
    relatedStrategy: 'macro-election-basket',
    notes: [],
    tags: ['elections', 'long-dated'],
    priceHistory: [0.548, 0.551, 0.554, 0.558, 0.561],
  },
  {
    id: 'pos-live-immunity-no',
    opportunityId: 'seed-immunity',
    environment: 'live',
    question: 'Will a federal court hearing mention Trump immunity this month?',
    category: 'Mentions',
    marketType: 'Courtroom mentions',
    side: 'NO',
    shares: 6181.82,
    stake: 3400,
    entryPrice: 0.55,
    currentPrice: 0.507,
    liquidationValue: 3134.18,
    unrealizedPnl: -265.82,
    status: 'review',
    openedAt: '2026-04-11T16:32:00.000Z',
    updatedAt: '2026-04-12T16:11:00.000Z',
    modelView: 'Still attractive, but event path is noisier than expected.',
    thesisAtEntry: 'Language model expected fewer direct references in hearing coverage.',
    exitGuidance: 'Reassess after next hearing preview. A move back through 0.53 warrants trimming.',
    relatedStrategy: 'mentions-event-parser',
    notes: [
      note(
        'note-pos-2',
        'Maya Patel',
        '2026-04-12T15:24:00.000Z',
        'decision',
        'Marked for review because event timing changed and implied volatility jumped.',
      ),
    ],
    tags: ['mentions', 'event-risk'],
    priceHistory: [0.544, 0.536, 0.529, 0.516, 0.507],
  },
]

export const seedPaperPositions: Position[] = [
  {
    id: 'pos-paper-mi-csk',
    opportunityId: 'opp-cricket-mi-csk',
    environment: 'paper',
    question: 'Will Mumbai Indians beat CSK in tonight’s IPL fixture?',
    category: 'Cricket',
    marketType: 'Moneyline',
    side: 'YES',
    shares: 4230.77,
    stake: 2200,
    entryPrice: 0.52,
    currentPrice: 0.534,
    liquidationValue: 2259.23,
    unrealizedPnl: 59.23,
    status: 'open',
    openedAt: '2026-04-12T15:02:00.000Z',
    updatedAt: '2026-04-12T16:12:00.000Z',
    modelView: 'Paper trial is validating the live thesis so far.',
    thesisAtEntry: 'Testing stake sizing logic before live deployment.',
    exitGuidance: 'Use as a promotion candidate if paper performance remains stable.',
    relatedStrategy: 'cricket-core-v1',
    notes: [],
    tags: ['paper', 'promotion-candidate'],
    priceHistory: [0.518, 0.521, 0.526, 0.531, 0.534],
  },
  {
    id: 'pos-paper-pa-2028',
    opportunityId: 'opp-ele-pa-2028',
    environment: 'paper',
    question: 'Will Democrats win Pennsylvania in the 2028 presidential election?',
    category: 'Elections',
    marketType: 'State outcome',
    side: 'YES',
    shares: 4630.63,
    stake: 2500,
    entryPrice: 0.54,
    currentPrice: 0.547,
    liquidationValue: 2532.95,
    unrealizedPnl: 32.95,
    status: 'open',
    openedAt: '2026-04-12T14:20:00.000Z',
    updatedAt: '2026-04-12T16:08:00.000Z',
    modelView: 'Signal remains stable across refreshes.',
    thesisAtEntry: 'Paper-first route for a long-dated political signal.',
    exitGuidance: 'Promote only after several stable refresh windows.',
    relatedStrategy: 'macro-election-basket',
    notes: [],
    tags: ['paper', 'macro'],
    priceHistory: [0.542, 0.543, 0.545, 0.546, 0.547],
  },
]

export const seedServices: ServiceHealth[] = [
  {
    id: 'svc-market-ingestion',
    name: 'Market ingestion',
    description: 'Gamma and market metadata sync',
    status: 'healthy',
    latencyMs: 182,
    lastHeartbeatAt: '2026-04-12T16:12:00.000Z',
    owner: 'Data infra',
    critical: true,
  },
  {
    id: 'svc-pricing',
    name: 'Price snapshots',
    description: 'Orderbook and midpoint refresh',
    status: 'healthy',
    latencyMs: 226,
    lastHeartbeatAt: '2026-04-12T16:12:00.000Z',
    owner: 'Execution',
    critical: true,
  },
  {
    id: 'svc-strategy',
    name: 'Strategy engine',
    description: 'Signal scoring and recommended sizing',
    status: 'healthy',
    latencyMs: 364,
    lastHeartbeatAt: '2026-04-12T16:11:00.000Z',
    owner: 'Research',
    critical: true,
  },
  {
    id: 'svc-execution',
    name: 'Execution gateway',
    description: 'Live order routing and paper fill simulation',
    status: 'healthy',
    latencyMs: 291,
    lastHeartbeatAt: '2026-04-12T16:12:00.000Z',
    owner: 'Execution',
    critical: true,
  },
  {
    id: 'svc-research',
    name: 'Research attachments',
    description: 'Document and web-link indexing',
    status: 'degraded',
    latencyMs: 1320,
    lastHeartbeatAt: '2026-04-12T15:58:00.000Z',
    owner: 'Ops',
    critical: false,
  },
]

export const seedLogs: LogEvent[] = [
  {
    id: 'log-1',
    timestamp: '2026-04-12T16:12:00.000Z',
    level: 'info',
    source: 'strategy-engine',
    message: 'Refreshed 8 candidate opportunities across 5 categories.',
  },
  {
    id: 'log-2',
    timestamp: '2026-04-12T16:09:00.000Z',
    level: 'info',
    source: 'execution-gateway',
    message: 'Paper fill simulation updated for 2 tracked strategies.',
  },
  {
    id: 'log-3',
    timestamp: '2026-04-12T16:03:00.000Z',
    level: 'warning',
    source: 'research-sync',
    message: 'Attachment indexing slowed. Web links remain available, uploaded file previews may lag.',
    actionRequired: false,
  },
  {
    id: 'log-4',
    timestamp: '2026-04-12T15:43:00.000Z',
    level: 'info',
    source: 'approval-flow',
    message: 'Soccer under 2.5 opportunity approved for live execution and is waiting for confirmation.',
    user: 'Maya Patel',
  },
  {
    id: 'log-5',
    timestamp: '2026-04-12T15:11:00.000Z',
    level: 'info',
    source: 'paper-routing',
    message: 'Pennsylvania election opportunity routed to paper trading for thesis validation.',
    user: 'Alex Chen',
  },
]

export const initialDashboardState: DashboardState = {
  liveCashBalance: 139800,
  paperCashBalance: 95300,
  liveRealizedPnl: 1820,
  paperRealizedPnl: 240,
  opportunities: seedOpportunities,
  livePositions: seedLivePositions,
  paperPositions: seedPaperPositions,
  services: seedServices,
  logs: seedLogs,
  pausedCategories: [],
  killSwitchEnabled: false,
  lastRefreshAt: '2026-04-12T16:12:00.000Z',
  refreshCount: 0,
}
